### ISSUE TITLE
LSPS0: What error code to return for unexpected / server errors

### ISSUE THREAD

**Issue by tnull** [BitcoinAndLightningLayerSpecs/lsp#86]
Currently, LSPS0 mentions that the LSP needs to respect the standard [JSON-RPC 2.0 error codes](https://www.jsonrpc.org/specification#error_object), but does not explicitly mention what code to send when an unexpected error occurs.

It could be argued that 
```
-32603     Internal error     Internal JSON-RPC error.
```

would be the right choice here, but we may also want to specify another code for unexpected errors?

**Comment by SeverinAlexB** [comment]
LSPS0 explicitly mentioning `-32602 Invalid Parameters Error` is an over-spec from our side IMO.

> it was a bit unclear to me what The LSP (..) MUST respect the JSON-RPC 2.0 standard error codes exactly means (does it need/is it allowed to use them, or is it only allowed to use codes from the 'server error' range? etc).

How I see the JSONRPC spec:
- `-32603 Internal error` is a generic unexpected error similar to the HTTP 500.
- `-32000 to -32099 | Server error` are custom errors we could specifically define. For example: We could say that `-32001` means "Payment required".

Looking at LSPS1 again, I think we are not adhering to the JSONRPC spec correctly. Instead of returning a [1000 error](https://github.com/BitcoinAndLightningLayerSpecs/lsp/blob/main/LSPS1/README.md?plain=1#L237) we should have returned an error in the range of `-32000 to -32099`. Not that I want to change the spec again but just to make you guys aware.

**Comment by SeverinAlexB** [comment]
Let me make a PR to update the spec
